CLcore/CLcore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('cytology.urls')),
]

CLcore/cytology/urls.py
from django.urls import path

from . import views

app_name = 'cytology'

urlpatterns = [
    path('list/', views.AListView.as_view(), name='list'),
    path('list/<int:pk>/', views.ADetailView.as_view(), name='detail'),
    path('<int:year>/', views.AYearArchiveView.as_view(), name='archive_year'),
    path('<int:year>/<str:month>/', views.AMonthArchiveView.as_view(), name='archive_month'),
    path('<int:year>/week/<int:week>/', views.AWeekArchiveView.as_view(), name='archive_week'),
    path('<int:year>/<str:month>/<int:day>/', views.ADayArchiveView.as_view(), name='archive_day'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('', views.IndexView.as_view(), name='home'),
]

CLcore/cytology/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Analysis(models.Model):
    reg = models.PositiveIntegerField(primary_key=True, verbose_name='РЕГ')  # РЕГ
    code = models.CharField(max_length=10, verbose_name='МО')  # CODE
    otdelen = models.CharField(max_length=10, verbose_name='ОТДЕЛЕНИЕ', null=True, blank=True)  # OTDELEN
    last_name = models.CharField(max_length=60, verbose_name='ФАМИЛИЯ', null=True, blank=True)  # ФАМИЛИЯ
    first_name = models.CharField(max_length=60, verbose_name='ИМЯ', null=True, blank=True)  # ИМЯ
    middle_name = models.CharField(max_length=60, verbose_name='ОТЧЕСТВО', null=True, blank=True)  # ОТЧЕСТВО
    gender = models.CharField(max_length=5, verbose_name='ПОЛ', null=True, blank=True)  # ПОЛ
    b_date = models.DateField(verbose_name='ДАТА РОЖДЕНИЯ', null=True, blank=True)  # ДАТА_РОЖД
    policy = models.CharField(max_length=18, null=True, blank=True)  # ПОЛИС
    snils = models.CharField(max_length=14, null=True, blank=True, verbose_name='СНИЛС')  # СНИЛС
    address = models.CharField(max_length=150, null=True, blank=True, verbose_name='АДРЕС')  # АДРЕС
    kl_diag = models.TextField(max_length=255, null=True, blank=True, verbose_name='КЛ_ДИАГ')  # КЛ_ДИАГ
    v_date = models.DateField(verbose_name='ДАТА ВЗЯТ', null=True, blank=True)  # ДАТА_ВЗЯТ
    p_date = models.DateField(verbose_name='ДАТА ПОСТ', null=True, blank=True)  # ДАТА_ПОСТ
    reg_date = models.DateField(verbose_name='ДАТА РЕГ', null=True, blank=True)  # ДАТА_РЕГ
    an_object = models.TextField(verbose_name='ОБЪЕКТ', null=True, blank=True)  # ОБЪЕКТ
    doctor = models.CharField(max_length=20, verbose_name='ДОКТОР', null=True, blank=True)  # ДОКТОР
    vyr_date = models.DateField(verbose_name='ДАТА ВЫРЕЗ', null=True, blank=True)#  ДАТА_ВЫРЕЗ
    macro = models.TextField(verbose_name='МАКРО', null=True, blank=True)  # МАКРО
    macro_p_a = models.CharField(max_length=20, verbose_name='МАКРО_п_а', null=True, blank=True)  # МАКРО_п_а
    micro = models.TextField(verbose_name='МИКРО', null=True, blank=True)  # МИКРО
    zakl = models.TextField(verbose_name='ЗАКЛ', null=True, blank=True)  # ЗАКЛ
    comment = models.TextField(verbose_name='КОММЕНТ', null=True, blank=True)  # КОММЕНТ
    mcode1 = models.CharField(max_length=6, verbose_name='кодмедусл1', null=True, blank=True)  # кодмедусл1
    mcode1_num = models.SmallIntegerField(verbose_name='кол_кодмедусл1', null=True, blank=True)  # кол_кодмедусл1
    mcode2 = models.CharField(max_length=6, verbose_name='кодмедусл2', null=True, blank=True)  # кодмедусл2
    mcode2_num = models.SmallIntegerField(verbose_name='кол_кодмедусл2', null=True, blank=True)  # кол_кодмедусл2
    code1 = models.CharField(max_length=5, verbose_name='код', null=True, blank=True)  # код
    complexity = models.SmallIntegerField(verbose_name='кол_кодмедусл2', null=True, blank=True)  # Сложность
    p_a = models.CharField(max_length=20, verbose_name='п_а', null=True, blank=True)  # п_а
    a_date = models.DateField(verbose_name='ДАТА ИССЛ', null=True, blank=True)  # ДАТА_ИССЛ
    # created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    # last_edit_date = models.DateTimeField(verbose_name='Дата посл. изменения', auto_now=True)

    def get_age(self):
        if self.b_date:
            age = self.v_date.year - self.b_date.year
        else:
            age = None
        return age

    def get_gender(self):
        if self.gender:
            g = self.gender[2:5]
        else:
            g = "-"
        return g

    def get_fio(self):
        return '%s %s. %s.' % (str(self.last_name), str(self.first_name)[0], str(self.middle_name)[0])

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

    def __str__(self):
        return '%s: [%s] %s %s' % (self.reg, self.a_date, self.last_name, self.first_name)

    class Meta:
        verbose_name = 'Исследование'
        verbose_name_plural = 'Исследования'
        ordering = ['-reg']

CLcore/cytology/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic.dates import (
    DayArchiveView,
    YearArchiveView,
    MonthArchiveView,
    WeekArchiveView,
)
from .models import Analysis
from django.db.models import Q


class IndexView(generic.ListView):
    template_name = "cytology/home.html"
    context_object_name = "latest_analysis_list"

    def get_queryset(self):
        """возвращает последние 10 записей"""
        return Analysis.objects.order_by("-v_date")[:10]


class AListView(generic.ListView):
    paginate_by = 25
    date_field = "v_date"

    def get_queryset(self):
        sd = self.request.GET.get("fromdate", "")
        ed = self.request.GET.get("todate", "")
        # start_date = datetime.date(sd)
        # end_date = datetime.date(ed)

        if not sd or not ed:
            object_list = Analysis.objects.order_by("-reg")
        else:
            object_list = Analysis.objects.filter(v_date__range=(sd, ed))
        return object_list


@method_decorator(login_required, name="dispatch")
class ADetailView(generic.DetailView):
    model = Analysis


class ADayArchiveView(DayArchiveView):
    queryset = Analysis.objects.all()
    date_field = "v_date"


class AYearArchiveView(YearArchiveView):
    queryset = Analysis.objects.all()
    date_field = "v_date"


class AMonthArchiveView(MonthArchiveView):
    queryset = Analysis.objects.all()
    date_field = "v_date"


class AWeekArchiveView(WeekArchiveView):
    queryset = Analysis.objects.all()
    date_field = "v_date"
    week_format = "%W"


class SearchResultsView(generic.ListView):
    model = Analysis
    paginate_by = 25
    template_name = "cytology/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q").upper()
        multiple_query = Q(Q(last_name__icontains=query) | Q(otdelen__icontains=query))
        object_list = Analysis.objects.filter(multiple_query)

        # object_list = Analysis.objects.filter(
        #     last_name__icontains=query  # поиск по фамилии
        #     #     # | Q(first_name__icontains=query)   # дополнительный поиск по имени
        #     #     # | Q(middle_name__icontains=query)  # дополнительный поиск по отчеству
        #     #     # | Q(address__icontains=query)      # дополнительный поиск по адресу
        # ).distinct()
        return object_list

CLcore/cytology/templates/cytology/analysis_archive_day.html
{% extends "cytology/wrapper.html" %}

{% block title %}Список: Исследования - дата {% endblock %}

{% block content %}
<h6 class="text-muted text-uppercase">
  <span>Найдено за указанную дату:</span>
</h6>
{% include 'cytology/object_list.html' %}

{% endblock %}

CLcore/cytology/templates/cytology/analysis_archive_month.html
{% extends "cytology/wrapper.html" %}

{% block title %}Список: Исследования - месяц{% endblock %}

{% block content %}
<h6 class="text-muted text-uppercase">
  <span>Найдено за {{ month|date:'F Y' }} г.:</span>
</h6>
{% include 'cytology/object_list.html' %}

{% endblock %}

CLcore/cytology/templates/cytology/analysis_archive_week.html
{% extends "cytology/wrapper.html" %}
{% load bootstrap5 %}

{% block content %}
<h6 class="text-muted text-uppercase">
  <span>Найдено за указанную неделю (Неделя {{ week|date:'W' }}):</span>
</h6>

{% include 'cytology/object_list.html' %}

<p>
    {% if previous_week %}
        Previous Week: {{ previous_week|date:"W" }} of year {{ previous_week|date:"Y" }}
    {% endif %}
    {% if previous_week and next_week %}--{% endif %}
    {% if next_week %}
        Next week: {{ next_week|date:"W" }} of year {{ next_week|date:"Y" }}
    {% endif %}
</p>

{% endblock %}

CLcore/cytology/templates/cytology/analysis_detail.html
{% extends "cytology/wrapper.html" %}
{% load bootstrap5 %}

{% block content %}


<h5>{{ object.code}} | Исследование №{{ object.reg }}
            {% if not object.a_date %}
            <span class="badge rounded-pill bg-warning text-dark">не завершено</span>
            {% else %}
            от {{ object.a_date }}
            {% endif %}
</h5>
<table class="table table-hover table-sm">
    <tbody>
    <tr>
        <td>Отделение:</td><td>{{ object.otdelen}} ({{ object.doctor}})</td>
    </tr>
    <tr {% if object.get_age < 16 %} class="table-info" {% endif %}>
        <td>ПАЦИЕНТ:</td>
        <td>{{ object.last_name}}
            {{ object.first_name}}
            {{ object.middle_name}},
            {{ object.get_gender }}.,

            {% if object.get_age %}
            {{ object.get_age }} лет,
            {% endif %}

            {% if object.p_date %} дата поступления {{ object.p_date|date:"d/m/y" }}.{% endif %}
        </td>
    </tr>

    <tr>
        <td>АДРЕС:</td>
        <td>
            {% if object.address %}
            {{ object.address }}
            {% else %}
            <span class="badge rounded-pill bg-warning text-dark">нет данных!</span>
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>МКБ, диагноз
            </td>
        <td>
            {% if not object.code1 %}
            <span class="badge rounded-pill bg-warning text-dark">код не указан</span>
            {% else %}
            {{ object.code1 }}
            {% endif %}
            ({{ object.kl_diag }})</td>
    </tr>
    <tr>
        <td>ОБЪЕКТ:</td><td>{{ object.an_object }}</td>
    </tr>
    <tr>
        <td>ДАТА ВЗЯТ:</td>
        <td>{{ object.v_date }}</td>
    </tr>
    <tr>
        <td>МАКРО:</td><td>{{ object.macro }} (п/а {{ object.macro_p_a}})</td>
    </tr>
    {% if object.micro %}
    <tr>
        <td>МИКРО:</td><td>{{ object.micro }}</td>
    </tr>
    {% endif %}
    <tr>
        <td>ЗАКЛ:</td><td>
        {% if not object.zakl %}
            <span class="badge rounded-pill bg-warning text-dark">нет данных!</span>
        {% else %}
            {{ object.zakl }}<br>(п/а: {{ object.p_a}})</td>
        {% endif %}
    </tr>

    </tbody>

</table>

{% if object.comment %}
<p>КОММЕНТ: {{ object.comment}}</p>
{% endif %}

<a class ="print-doc noprint" href="javascript:(print());">
    <button type="button" class="btn btn-sm btn-outline-secondary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-printer" viewBox="0 0 16 16">
          <path d="M2.5 8a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1z"/>
          <path d="M5 1a2 2 0 0 0-2 2v2H2a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h1v1a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-1h1a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-1V3a2 2 0 0 0-2-2H5zM4 3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2H4V3zm1 5a2 2 0 0 0-2 2v1H2a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-1v-1a2 2 0 0 0-2-2H5zm7 2v3a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1z"/>
        </svg>&nbsp;
        Распечатать
    </button>
</a>

{% endblock %}

CLcore/cytology/templates/cytology/analysis_list.html
{% extends "cytology/wrapper.html" %}

{% block title %}Список: Исследования{% endblock %}

{% block content %}

{% include 'cytology/object_list.html' %}


{% endblock %}

CLcore/cytology/templates/cytology/footer.html
{% load bootstrap5 %}


<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">ОБУЗ КОМКБ. 2022 г.</span>
  </div>
</footer>

CLcore/cytology/templates/cytology/home.html
{% extends "cytology/wrapper.html" %}
{% block content %}
{% include 'cytology/object_list.html' %}
{% endblock %}

CLcore/cytology/templates/cytology/object_list.html
{% load bootstrap5 %}


{% if object_list %}

{% if page_obj.has_other_pages %}
    {% bootstrap_pagination page_obj size="small" %}
{% endif %}

<div class="table-responsive">
<table class="table table-striped table-sm">
    <thead>
    <tr class="table-secondary">
        <th scope="col">Рег.№</th>
        <th scope="col" style="text-align: center;">Отделение</th>
        <th scope="col">Дата взят.</th>
        <th scope="col">Фамилия, инициалы</th>
        <th scope="col" style="text-align: center;">Пол</th>
        <th scope="col" style="text-align: center;">Возр.</th>
    </tr>
    </thead>
    <tbody>
    {% for analysis in object_list %}

    <tr {% if analysis.get_age < 16 %} class="table-info" {% endif %}>
        <td>
            <a href="/list/{{ analysis.pk }}/">
            {{ analysis.reg }}
            </a>
        </td>
        <td style="text-align: center;">
            {{ analysis.otdelen }}
        </td>
        <td>
            {{ analysis.v_date|date }}
        </td>
        <td>
            {{ analysis.get_fio }}
        </td>
        <td style="text-align: center;">
            {{ analysis.get_gender }}
        </td>
        <td style="text-align: center;">
            {% if analysis.get_age %}
            {{ analysis.get_age }}
            {% else %} -
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</div>


{% else %}
    <p>К сожалению, записей не найдено.</p>
{% endif %}

CLcore/cytology/templates/cytology/search_results.html
{% extends "cytology/wrapper.html" %}
{% load bootstrap5 %}

{% block title %}Поиск: Исследования{% endblock %}

{% block content %}


{% if object_list %}

<div class="table-responsive">
<table class="table table-striped table-sm">
    <thead>
    <tr class="table-secondary">
        <th scope="col">Рег.№</th>
        <th scope="col" style="text-align: center;">Отделение</th>
        <th scope="col">Дата взят.</th>
        <th scope="col">Фамилия, инициалы</th>
        <th scope="col" style="text-align: center;">Пол</th>
        <th scope="col" style="text-align: center;">Возр.</th>
    </tr>
    </thead>
    <tbody>
    {% for analysis in object_list %}

    <tr {% if analysis.get_age < 16 %} class="table-info" {% endif %}>
        <td>
            <a href="/list/{{ analysis.id }}/">
            {{ analysis.reg }}
            </a>
        </td>
        <td style="text-align: center;">
            {{ analysis.otdelen }}
        </td>
        <td>
            {{ analysis.v_date|date }}
        </td>
        <td>
            {{ analysis.get_fio }}
        </td>
        <td style="text-align: center;">
            {{ analysis.get_gender }}
        </td>
        <td style="text-align: center;">
            {% if analysis.get_age %}
            {{ analysis.get_age }}
            {% else %} -
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</div>

{% if page_obj.has_other_pages %}
{% if page_obj.has_previous %}
<a class="navlink" href="?page={{ page_obj.previous_page_number }}&q={{ request.GET.q }}">Предыдущая страница</a>
{% endif %}

{% if page_obj.has_next %}
    <a class="navlink" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">Следующая страница</a>
{% endif %}

{% endif %}

{% else %}
    <p>К сожалению, записей не найдено.</p>
{% endif %}

{% endblock %}

CLcore/cytology/templates/cytology/wrapper.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>

    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet"  media = "screen, print">
  </head>
  <body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow noprint">

  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="{% url 'cytology:home' %}">
    Гист<svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="white" class="cell" viewBox="0 0 33 30">
        <g>
            <path d="M15.913,0C7.138,0,0,7.139,0,15.913c0,8.774,7.138,15.913,15.913,15.913c8.776,0,15.913-7.139,15.913-15.913
                C31.826,7.139,24.689,0,15.913,0z M15.913,29.294c-7.379,0-13.38-6.002-13.38-13.381c0-7.377,6.001-13.38,13.38-13.38
                c7.379,0,13.381,6.003,13.381,13.38C29.294,23.292,23.292,29.294,15.913,29.294z"/>
            <circle cx="21.332" cy="17.888" r="3.874"/>
            <circle cx="12.699" cy="7.868" r="2.877"/>
            <circle cx="9.607" cy="17.493" r="3.479"/>
            <circle cx="15.714" cy="24.333" r="1.466"/>
            <circle cx="21.941" cy="9.898" r="1.583"/>
            <circle cx="16.178" cy="13.885" r="1.341"/>
        </g>
        </svg>логия</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
          data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <form class="form-control form-control-light- w-100 rounded-0 border-0"
        action="{% url 'cytology:search_results' %}"
        method="get">
    <input class="form-control form-control-dark w-100 rounded-0 border-0" name="q"
           type="text" placeholder="Поиск по фамилии пациента ИЛИ отделению" aria-label="Поиск по фамилии">
  </form>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      {% if user.is_authenticated %}

      <a class="nav-link px-3" href="{% url 'logout' %}">{{ user.first_name }} {{ user.last_name }} [Выход]</a>
      {% else %}
      <a class="nav-link px-3" href="{% url 'login' %}">Вход</a>
      {% endif %}
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse noprint">
      <div class="position-sticky pt-5 noprint">
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
          <span>Записи:</span>
        </h6>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'cytology:home' %}">
              Последние 10
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cytology:list' %}">
              Все
            </a>
          </li>
        </ul>
        <!--
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
          <span>Фильтр по дате:</span>
        </h6>
        <form method="GET">
          {% csrf_token %}
          <div class="form-row px-2" >
            <div class="form-group col-md6">
              <label for="Inputdate">От:</label>
              <input type="date" name="fromdate" class="form-control" id="Inputdate"/>
            </div>
            <div class="form-group col-md6">
              <label for="Inputdate">До:</label>
              <input type="date" name="todate" class="form-control" id="Inputdate"/>
            </div>
            <hr>
            <button class="btn btn-primary" type="submit">Применить</button>
        </form>
        -->
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
          <span>Настройки:</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="/admin/">
              <span data-feather="file-text" class="align-text-bottom"></span>
              Панель администратора
            </a>
          </li>
          <hr>
          
        </ul>

      </div>
      <footer class="footer mt-auto bg-light">
        <div class="container">
          <span class="text-muted">ОБУЗ КОМКБ. 2022 г.</span>
        </div>
      </footer>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <!--h1 class="h2">Исследования</h1-->
      </div>
      

      <div id="content">
      {% block content %}
      <h2>B</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>text</td>
              <td>random</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>placeholder</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>placeholder</td>
              <td>tabular</td>
              <td>information</td>
              <td>irrelevant</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>text</td>
              <td>placeholder</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>visual</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>random</td>
              <td>tabular</td>
              <td>information</td>
              <td>text</td>
            </tr>
          </tbody>
        </table>
      </div>
      {% endblock %}
      </div>

    </main>
  </div>
</div>

</nav>

{% bootstrap_javascript %}


  </body>

</html>